from pqueue import PQueue
p =  PQueue()
p.enqueue("HELLO",1)
p.enqueue("H",2)
p.enqueue("E",5)
p.enqueue("L",3)
p.enqueue("O",3)
p.enqueue("Sample",9)

print(p.size())
print(p.dequeue())
print(p.size())
print(p.dequeue())
print(p.dequeue())
print(p.dequeue())
print(p.size())
